title: AGROFORESTRY
description: Official AGROFORESTRY project page

url: https://AGROFORESTERIE.github.io
# paginate_path: "blog/page:num/"
# permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate-v2]
# paginate: 5
# paginate_path: "./news/page:num/"
pagination:
  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true
  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false
  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 5
# The permalink structure for the paginated pages (this can be any level deep)
  #permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files 
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: News
    url: /news/news.html 
  - title: Contact
    url: /contact

social:
  github: 
  twitter: 
  facebook:
  email: raphael.conde-salazar@inrae.fr
  linkedin: 

google_analytics: 

disqus:
    shortname: raphaël
