title: AGROFORESTRY
description: Official AGROFORESTRY project page

url: https://AGROFORESTERIE.github.io
paginate_path: "news/page:num/"
permalink: news/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: News
    url: /news/index.html
  - title: Contact
    url: /contact
  - title: Download
    url: /download

social:
  github: 
  twitter: 
  facebook:
  email: raphael.conde-salazar@inrae.fr
  linkedin: 

google_analytics: 

disqus:
    shortname: agroforestry
